name: Load POC Vault Secrets

on:
  workflow_call:
    secrets:
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true

jobs:
  load-secrets:
    name: Load secrets from 1Password (Test vault)
    runs-on: ubuntu-latest

    steps:
      - name: Load secrets from 1Password
        id: op
        uses: 1password/load-secrets-action@7ce42673ba9ed69053d678faeba29ea36bd25755  # v4.0.0
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DB_USERNAME: op://Test/DB_PASS/username
          DB_PASSWORD: op://Test/DB_PASS/password
        with:
          export-env: true
