name: Load POC Vault Secrets

on:
  workflow_call:
    outputs:
      db_username:
        description: "Database username"
        value: ${{ jobs.load-secrets.outputs.db_username }}
      db_password:
        description: "Database password"
        value: ${{ jobs.load-secrets.outputs.db_password }}

jobs:
  load-secrets:
    name: Load secrets from 1Password (Test vault)
    runs-on: ubuntu-latest

    outputs:
      db_username: ${{ steps.op.outputs.DB_USERNAME }}
      db_password: ${{ steps.op.outputs.DB_PASSWORD }}

    steps:
      - name: Load secrets from 1Password
        id: op
        uses: 1password/load-secrets-action@7ce42673ba9ed69053d678faeba29ea36bd25755  # v4.0.0
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DB_USERNAME: op://Test/DB_PASS/username
          DB_PASSWORD: op://Test/DB_PASS/password
        with:
          export-env: false
